return {
	menu_id = "clientside_stealth_options",
	title = "cst_options_title",
	desc = "cst_options_desc",
	items = {
		{
			setting = "enabled",
			always = true,
			title = "cst_options_enabled_title",
			desc = "cst_options_enabled_desc",
		},
		{ divider = true },
		{ heading = "cst_options_targets" },
		{
			setting = "player",
			title = "cst_options_player_title",
			desc = "cst_options_player_desc",
			indent = true,
		},
		{ setting = "bag", title = "cst_options_bag_title", desc = "cst_options_bag_desc", indent = true },
		{
			setting = "corpse",
			title = "cst_options_corpse_title",
			desc = "cst_options_corpse_desc",
			indent = true,
		},
		{
			setting = "hostage",
			title = "cst_options_hostage_title",
			desc = "cst_options_hostage_desc",
			indent = true,
		},
		{
			setting = "vehicle",
			title = "cst_options_vehicle_title",
			desc = "cst_options_vehicle_desc",
			indent = true,
		},
		{
			setting = "drill",
			title = "cst_options_drill_title",
			desc = "cst_options_drill_desc",
			indent = true,
		},
		{
			setting = "prop",
			title = "cst_options_prop_title",
			desc = "cst_options_prop_desc",
			indent = true,
		},
		{
			setting = "npc",
			title = "cst_options_npc_title",
			desc = "cst_options_npc_desc",
			indent = true,
		},
		{ divider = true },
		{ heading = "cst_options_actions" },
		{
			setting = "intimidation",
			title = "cst_options_intimidation_title",
			desc = "cst_options_intimidation_desc",
			indent = true,
		},
		{
			setting = "dart",
			title = "cst_options_dart_title",
			desc = "cst_options_dart_desc",
			indent = true,
		},
		{
			setting = "camera_loop",
			title = "cst_options_camera_loop_title",
			desc = "cst_options_camera_loop_desc",
			indent = true,
		},
		{
			setting = "bag_handling",
			title = "cst_options_bag_handling_title",
			desc = "cst_options_bag_handling_desc",
			indent = true,
		},
		{
			setting = "bag_secure",
			title = "cst_options_bag_secure_title",
			desc = "cst_options_bag_secure_desc",
			indent = 2,
			parent = "bag_handling",
		},
		{
			setting = "equipment",
			title = "cst_options_equipment_title",
			desc = "cst_options_equipment_desc",
			indent = true,
		},
		{ divider = true },
		{
			setting = "lua_networking",
			title = "cst_options_lua_networking_title",
			desc = "cst_options_lua_networking_desc",
			always = true,
		},
		{ heading = "cst_connections_none", connection = true },
		{ page = "lobby" },
	},

	lobby = { menu_id = "clientside_stealth_lobby", title = "cst_lobby_title", desc = "cst_lobby_desc" },
}
